project_id = "tbyhmqrfdhbxqrjstfns"

[functions.create-donation]
verify_jwt = false

[functions.seed-content]
verify_jwt = false

[functions.run-cycle]
verify_jwt = false

[functions.sitemap]
verify_jwt = false

[functions.create-donation-checkout]
verify_jwt = false

[functions.track-donation-intent]
verify_jwt = false

[functions.stripe-webhook]
verify_jwt = false
